import LandingNavbar from "@/components/landing/LandingNavbar";
import Footer from "@/components/landing/Footer";
import useSEO from "@/hooks/useSEO";

const MedicalDisclaimer = () => {
  useSEO({
    title: "Medical Disclaimer – Aidera",
    description: "Aidera provides AI-generated health guidance only. It does not diagnose, treat, or replace licensed medical professionals. Read our full medical disclaimer.",
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      <LandingNavbar />
      <main className="container mx-auto px-4 py-20 max-w-[850px]">
        <h1 className="font-display text-4xl font-bold mb-2">Medical Disclaimer</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 3, 2026</p>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">Introduction</h2>
          <p className="text-muted-foreground leading-relaxed">
            Aidera is an artificial intelligence–powered health assistant designed to help users better understand medical documents, ask general health questions, and receive supportive, AI-generated guidance. This Medical Disclaimer governs your use of the Aidera platform, including its website, applications, and all related services. By accessing or using Aidera, you acknowledge and agree to the terms outlined in this disclaimer.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">No Medical Advice</h2>
          <p className="text-muted-foreground leading-relaxed">
            The content provided by Aidera — including text responses, document analyses, health insights, and any other output — is generated by artificial intelligence for informational and educational purposes only. It does <strong className="text-foreground">not</strong> constitute medical advice, diagnosis, treatment, or prescription. Aidera does not diagnose medical conditions, recommend treatments, prescribe medications, or provide clinical opinions. No information provided by Aidera should be interpreted as a substitute for the judgment of a qualified healthcare professional.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">No Doctor-Patient Relationship</h2>
          <p className="text-muted-foreground leading-relaxed">
            Use of Aidera does not create a doctor-patient relationship, therapist-client relationship, or any other professional healthcare relationship between you and Aidera, its developers, affiliates, or partners. Aidera is a technology tool — not a healthcare provider. You should always seek the advice of a licensed physician, specialist, or other qualified healthcare provider with any questions you may have regarding a medical condition or treatment plan.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">Emergency Notice</h2>
          <div className="bg-destructive/10 border border-destructive/30 rounded-xl p-5">
            <p className="text-foreground font-medium leading-relaxed">
              If you are experiencing a medical emergency, call your local emergency services (such as 911 in the United States) or go to the nearest emergency room immediately. Do not rely on Aidera or any AI-based tool for emergency medical situations. Aidera is not designed to handle urgent or life-threatening health events.
            </p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">Accuracy of Information</h2>
          <p className="text-muted-foreground leading-relaxed">
            While Aidera strives to provide accurate, up-to-date, and evidence-informed health information, AI-generated content may contain errors, omissions, or outdated data. Medical science evolves continuously, and AI systems have inherent limitations. Aidera makes no warranties or representations regarding the completeness, accuracy, reliability, or suitability of any information provided. You acknowledge that any reliance on such information is at your own risk.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="font-display text-2xl font-semibold mb-3">User Responsibility</h2>
          <p className="text-muted-foreground leading-relaxed">
            You are solely responsible for any decisions you make based on the information provided by Aidera. Before making any health-related decisions — including starting, stopping, or modifying any treatment, medication, exercise, or dietary plan — you must consult a licensed healthcare professional. Aidera shall not be held liable for any health outcomes, injuries, losses, or damages arising from your use of, or reliance on, any content generated by the platform.
          </p>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default MedicalDisclaimer;
